services:
  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "8000:8000"
    networks:
      - etl_net

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pipeline_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - etl_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pipeline_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow:
    build:
      context: ./airflow
    container_name: airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@postgres:5432/pipeline_db
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: >
        bash -c "airflow standalone"
    networks:
      - etl_net
    depends_on:
        postgres:
            condition: service_healthy
        api:
            condition: service_started

volumes:
  pgdata:

networks:
  etl_net:
